version: "3.8"
name: "upsilon_cities_dev"
networks:
  upsilon-network:
    name: "upsilon_cities_support_upsilon-network"
    external: true

services:
  backend_admin:
    build:
      context: ../backend_admin
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../backend_admin:/var/www/html:cached
    command: sleep infinity
    ports:
      - "8100:8000"
    environment:
      DB_HOST: postgres_admin
      DB_PORT: 5532
      DB_DATABASE: admin_db
      DB_USERNAME: admin
      DB_PASSWORD: adminpass
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - upsilon-network

  city_engine:
    build:
      context: ../city_engine
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../city_engine:/workspace:cached
    command: sleep infinity
    ports:
      - "8200:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_city:5432/city_db
      SPRING_DATASOURCE_USERNAME: city
      SPRING_DATASOURCE_PASSWORD: citypass
      JWT_SERVICE: http://jwt_service:7000
    networks:
      - upsilon-network


  jwt_service:
    build:
      context: ../jwt_service
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../jwt_service:/workspace:cached
    command: sleep infinity
    ports:
      - "7000:7000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - upsilon-network

  frontend:
    build:
      context: ../frontend
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../frontend:/workspace:cached
    command: sleep infinity
    ports:
      - "5173:5173"
    networks:
      - upsilon-network
